version: "3"
services:
  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.11
    restart: always
    container_name: virtuoso
    volumes:
      - ./virtuoso:/database # directory to persist the Virtuoso database. If empty dir, a new database will be created
    environment:
      - DBA_PASSWORD=CONDUCTOR_PASSWORD
      - SPARQL_UPDATE=false
    ports:
      - "8899:8890"
      - "1133:1111"